port 80

# Maximum request-body size in bytes (default: 1048576)
# max_body_size 1048576

content_path  /Users/gabitoju/Library/CloudStorage/Dropbox/gabitoju.github.io
mime_types_path /Users/gabitoju/projects/c/srv/mime.types
real_ip_header CF-Connecting-IP

# Execute .pol files through Polonio CGI.
cgi_handler .pol /Users/gabitoju/projects/cpp/polonio/build/polonio
