port 8080

# Maximum request-body size in bytes (default: 1048576)
# max_body_size 1048576

content_path /var/www/srv
mime_types_path /etc/srv/mime.types
access_log_path /var/log/gabitojusrv/access.log
error_log_path /var/log/gabitojusrv/error.log
real_ip_header X-Forwarded-For

# Execute .pol files through Polonio CGI.
# cgi_handler .pol /usr/local/bin/polonio
